services:
  - type: web
    name: todo-app-backend
    env: node
    plan: free
    buildCommand: cd client && npm install && npm run build && cd .. && npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
